version: "2"
services:
  db:
    restart: always
    image: mongo:3.6.1
    volumes:
    - ${DATA_DIR}:/data/db
    networks:
    - back
    labels:
      io.rancher.container.hostname_override: container_name

  client:
    restart: always
    image: akocloud/akocloud-client:latest
    volumes:
    - ${LOGDATA_DIR}:/opt/buda/akocloud/logs
    labels:
      io.rancher.container.hostname_override: container_name

  api:
    restart: always
    image: akocloud/akocloud-api:1.0.1
    volumes:
    - ${LOGDATA_DIR}/api:/opt/buda/akocloud/logs
    - ${TMP_DATA_DIR}:/opt/buda/akocloud/tmp
    - ${FILES_DATA_DIR}:/opt/buda/akocloud/files
    - ${PUBLIC_DATA_DIR}:/opt/buda/akocloud/public
    environment:
      MIIMETIQ_AMQP_HOSTNAME: $MIIMETIQ_AMQP_HOSTNAME
      MIIMETIQ_AMQP_USER: $MIIMETIQ_AMQP_USER
      MIIMETIQ_AMQP_PASSWORD: $MIIMETIQ_AMQP_PASSWORD
      MIIMETIQ_API_URL: $MIIMETIQ_API_URL
      MIIMETIQ_API_USER: $MIIMETIQ_API_USER
      MIIMETIQ_API_PASSWORD: $MIIMETIQ_API_PASSWORD
      DB_CONFIG: mongodb://db/akocloud
      CLIENT_URL: $CLIENT_URL
      API_URL: $API_URL
      SMTP_USER: $SMTP_USER
      SMTP_PASS: $SMTP_PASS
      SMTP_HOST: $SMTP_HOST
      SMTP_FROM: $SMTP_FROM
      AKOCLOUD_HOST: $AKOCLOUD_HOST
      AKOCLOUDH_API_URL: $AKOCLOUDH_API_URL
      SYSTEM_CONTEXT_TOKEN: $SYSTEM_CONTEXT_TOKEN
      SYSTEM_APPLICATION_ID: $SYSTEM_APPLICATION_ID
      REPORT_SERVICE_URL: http://report:5000
      AWS_KEY: $AWS_KEY
      AWS_SECRET_KEY: $AWS_SECRET_KEY
      AWS_REGION: $AWS_REGION
      AWS_BUCKET: $AWS_BUCKET
    depends_on:
    - db
    labels:
      io.rancher.container.hostname_override: container_name

  sslproxy:
    image: nginx:1.9.9
    tty: true
    stdin_open: true
    links:
    - client:client
    - api:api

  lb:
    image: rancher/load-balancer-service
    tty: true
    stdin_open: true
    ports:
    - 80:80/tcp
    - 443:443/tcp
    labels:
      io.rancher.loadbalancer.target.sslproxy: 443=443
      io.rancher.loadbalancer.target.sslproxy: 80=80
    links:
    - sslproxy:sslproxy
