version: "2"
catalog:
  name: AKOCLOUD
  version: 1.0.0
  description: |
    Akocloud asset.
  uuid: akocloud-0
  questions:
  - variable: LOGDATA_DIR
    description: "Log data directory"
    label: "Log data Storage directory"
    type: "string"
  - variable: TMP_DATA_DIR
    description: "Temporal data directory"
    label: "Temporal data Storage directory"
    type: "string"
  - variable: FILES_DATA_DIR
    description: "File path data directory"
    label: "File path data directory"
    type: "string"
  - variable: PUBLIC_DATA_DIR
    description: "Public file path data directory"
    label: "Public file path data directory"
    type: "string"
  - variable: DATA_DIR
    description: "Data directory"
    label: "Data Storage directory"
    type: "string"
    required: true
  - variable: MIIMETIQ_AMQP_HOSTNAME
    description: "Miimetiq amqp hostname"
    label: "MIIMETIQ hostname"
    type: "string"
    required: true
  - variable: MIIMETIQ_AMQP_USER
    description: "Miimetiq amqp username"
    label: "MIIMETIQ username"
    type: "string"
    required: true
  - variable: MIIMETIQ_AMQP_PASSWORD
    description: "Miimetiq amqp password"
    label: "MIIMETIQ password"
    type: "password"
    required: true
  - variable: MIIMETIQ_API_URL
    description: "Miimetiq api URL"
    label: "MIIMETIQ api URL"
    type: "string"
    required: true
  - variable: MIIMETIQ_API_USER
    description: "Miimetiq api User"
    label: "MIIMETIQ api User"
    type: "string"
    required: true
  - variable: MIIMETIQ_API_PASSWORD
    description: "Miimetiq api Password"
    label: "MIIMETIQ api Password"
    type: "password"
    required: true
  - variable: CLIENT_URL
    description: "Client URL"
    label: "Client Url"
    type: "string"
    required: true
  - variable: API_URL
    description: "API url"
    label: "API url"
    type: "string"
    required: true
  - variable: SMTP_USER
    description: "SMTP user"
    label: "SMTP user"
    type: "string"
    required: true
  - variable: SMTP_PASS
    description: "SMTP password"
    label: "SMTP password"
    type: "password"
    required: true
  - variable: SMTP_HOST
    description: "SMTP host"
    label: "SMTP host"
    type: "string"
    required: true
  - variable: SMTP_FROM
    description: "SMTP From"
    label: "SMTP From"
    type: "string"
    required: true
  - variable: AKOCLOUD_HOST
    description: "Akocloud host"
    label: "Akocloud host"
    type: "string"
    required: true
  - variable: AKOCLOUDH_API_URL
    description: "Akocloud homologate url"
    label: "Akocloud homologate url"
    type: "string"
    required: true
  - variable: AWS_KEY
    description: "AWS key"
    label: "AWS key"
    type: "string"
    required: true
  - variable: AWS_SECRET_KEY
    description: "AWS secret key"
    label: "AWS secret key"
    type: "string"
    required: true
  - variable: AWS_REGION
    description: "AWS region "
    label: "AWS region "
    type: "string"
    required: true
  - variable: AWS_BUCKET
    description: "AWS bucket "
    label: "AWS bucket "
    type: "string"
    required: true
  - variable: AMQP_QUEUE_SUFIX
    description: "AMQP queue sufix"
    label: "AMQP queue sufix"
    type: "string"
    required: false
  - variable: SYSTEM_CONTEXT_TOKEN
    description: "System internal token"
    label: "System internal token"
    type: "string"
    required: true
  - variable: SYSTEM_APPLICATION_ID
    description: "System internal application ID"
    label: "System internal application ID"
    type: "string"
    required: true
